### ISSUE TITLE
make sure all math operations are safe

### ISSUE THREAD

**Issue by askmike** [ploutos-capital/ico-alpha#2]
We need to guard this ourselves, this is tricky to do since not checking this leaves the contract open to attacks. Here is a library a lot of people rely upon:

https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/math/SafeMath.sol

**Comment by ale316** [comment]
That looks good and simple.

**Comment by ale316** [comment]
We close this as we're using Zeppelin which already includes it
